// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbaaxDQIKKHg10q14q-Buorvm0-QyRNUQ',
    appId: '1:659879338452:web:590858578b7d17877ab641',
    messagingSenderId: '659879338452',
    projectId: 'sandesh-5fcac',
    authDomain: 'sandesh-5fcac.firebaseapp.com',
    storageBucket: 'sandesh-5fcac.appspot.com',
    measurementId: 'G-DV10V5XKVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByMJ12hsnwZzFeKFXU3DhmaeI_-1g42IE',
    appId: '1:659879338452:android:fd7f4141d08500ea7ab641',
    messagingSenderId: '659879338452',
    projectId: 'sandesh-5fcac',
    storageBucket: 'sandesh-5fcac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fyVnfX2RBRDKjOXHbLQvBcDh2s4NTSc',
    appId: '1:659879338452:ios:4ad3d05856a60c527ab641',
    messagingSenderId: '659879338452',
    projectId: 'sandesh-5fcac',
    storageBucket: 'sandesh-5fcac.appspot.com',
    iosClientId: '659879338452-7d0cjr2vtk4ekikimaa6imabuaco44pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1fyVnfX2RBRDKjOXHbLQvBcDh2s4NTSc',
    appId: '1:659879338452:ios:79fa08c4033c9f3c7ab641',
    messagingSenderId: '659879338452',
    projectId: 'sandesh-5fcac',
    storageBucket: 'sandesh-5fcac.appspot.com',
    iosClientId: '659879338452-17ce17hml2dtgojflq29c0e48ep0qjaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandesh.RunnerTests',
  );
}
